name: CI-windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements-dev.txt
          git submodule update --init

      - name: install from source
        run: python setup.py install